#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check docker') {
        sh "docker --version"
    }
    
    stage('down') {
    	sh "docker-compose -f ./ci_cd/dev/docker-compose.yml down -v --remove-orphans"
    }

    stage('deploy') {
        sh "docker-compose -f ./ci_cd/dev/docker-compose.yml up --build -d"
    }
}
